### ISSUE TITLE
Error: The method 'pumpWithDuration' isn't defined for the class 'WidgetTester'. - 'WidgetTester' is from 'package:flutter_test/src/widget_tester.dart'

### ISSUE THREAD

**Issue by lapphong** [ntminhdn/Flutter-Riverpod-Lean-Architecture#1]
- Dạ hi anh, anh cho em xin hỏi về cái integration_test ạ. Khi mà e cấu trúc lại thư mục integration_test\features\login\t1_login_failed.dart để tiện test các tính năng khác, thì nó bị lỗi tất cả các hàm extension mà mình định nghĩa,không biết là có cách nào khắc phục không anh.

![image](https://github.com/ntminhdn/Flutter-Riverpod-Lean-Architecture/assets/74809207/806e6b43-687c-448f-98f6-027f15feaa21)

- Lệnh run sau khi cấu trúc: 
`
flutter drive \
	--driver=integration_test/test_driver/integration_driver.dart \
	--target integration_test/features/login/t1_login_failed.dart \
	-d chrome
 `

**Comment by mynavitechtus-minhnt3** [comment]
@lapphong lỗi này thường do import/export sai path. E thử kiểm tra lại path trong file `integration_test/common/index.dart` và xem thử đã import file `index.dart` vào file test chưa. Nếu ko được thì fork repo này rồi gửi link a check thử chứ a ko tái hiện được lỗi. Nếu được thì cung cấp a thêm Flutter version e đang dùng nữa.

**Comment by lapphong** [comment]
Hi anh @minhnt3, e đã kiểm tra lại đường dẫn và không có sai xót a. E đã fork project về và tái hiện lỗi như sau

- Link: [https://github.com/lapphong/Flutter-Riverpod-Lean-Architecture](https://github.com/lapphong/Flutter-Riverpod-Lean-Architecture)

- Phiên bản:
```
Flutter 3.19.4 
Dart 3.3.2
```
- Các bước tái hiện lại lỗi: e tạo thêm floder `integration_test/features/login/` và kéo file `t1_login_failed.dart` vào trong như hình bên dưới:

![image](https://github.com/ntminhdn/Flutter-Riverpod-Lean-Architecture/assets/74809207/f196dab2-b694-4860-8c1c-11fca9c5a10d)

- Đổi lại lệnh run trong `makefile`
```
flutter drive \
--driver=integration_test/test_driver/integration_driver.dart \
--target integration_test/features/login/t1_login_failed.dart \
--flavor develop --debug --dart-define-from-file=dart_defines/develop.json
```

-> Sau khi run thì nó bị lỗi như trên

![image](https://github.com/ntminhdn/Flutter-Riverpod-Lean-Architecture/assets/74809207/b991595d-b3b6-4ee7-96dd-8ded18685fba)

Em có tham khảo trên docs thì thấy người ta bảo nên như này [Package Structure](https://github.com/flutter/flutter/tree/master/packages/integration_test#package-structure). Không biết là trong `integration_test` có một số quy tắc nào không ? Do e đọc 9 bài Bách khoa toàn thư thấy thích quá nên học thử về test cũng mới học tới `integration_test` nên không biết nhiều 😂.

**Comment by mynavitechtus-minhnt3** [comment]
@lapphong a thử clone proj e về và chạy thử trên máy ảo android và ios đều ko gặp lỗi như e. Cái link package structure đó nó nói quy tắc là folder integration_test phải đồng cấp với folder lib và ko thuộc folder test thôi e.

**Comment by lapphong** [comment]
Em đã fix lỗi bằng cách gỡ flutter hiện tại và cài đặt lại. Hiện tại nó đã chạy được trên android và ios, nhưng do đặc thù công việc yêu cầu chạy trên bản web nữa, nhưng bản web thì vẫn còn dính lỗi đó. Em có xem trên [Link](https://github.com/flutter/flutter/issues/102469#issue-1213690308 ) này thì thấy cộng đồng đã báo cáo từ rất lâu nhưng chưa được fix, nên chắc phải chờ thêm thời gian.
Cám ơn anh đã giành thời gian tìm vấn đề sửa lỗi giúp em. Chúc anh nhiều sức khỏe và đầu tuần tràn đầy năng lượng. Em xin phép đóng issue này ạ.

**Comment by mynavitechtus-minhnt3** [comment]
@lapphong Repo này chưa có support bản web, a cũng chưa test trên web nên a sợ tiềm ẩn nhiều lỗi. Cảm ơn e đã báo cáo lỗi. A sẽ cân nhắc support cả web trong tương lai. Chúc em nhiều sức khoẻ và niềm vui.
